config/routes.rb
Rails.application.routes.draw do
  resources :employees

  resources :departments

  root 'departments#index'
   get 'orderbyage', to: 'employees#orderbyage'
   get 'orderbydepartment', to: 'employees#orderbydepartment'
   get 'orderbysalary', to: 'employees#orderbysalary'
   get 'retired', to: 'employees#retired'
   get 'topsalary', to: 'employees#topsalary'
   get 'topsalary5', to: 'employees#topsalary5'
   get 'old5', to: 'employees#old5'
   get 'topandlast', to: 'employees#topandlast'
   get 'leastinretired', to: 'employees#leastinretired'
   get 'toppaidbydepartment', to: 'employees#toppaidbydepartment'

end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :employees
  validates :department_name, presence: true
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :department
  validates :name,:email,:age_in_years, :salary_in_dollars, :department , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:department_name)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end
########################################
# GET /orderbyage
  def orderbyage
    @employee = Employee.order(:age_in_years)
  end
  
  # GET /orderbydepartment
  def orderbydepartment
    @employee = Employee.order('department_id')
  end
  
  # GET /orderbysalary
  def orderbysalary
    @employee = Employee.order('salary_in_dollars')
  end
  
  # GET /retired
  def retired
    @employee = Employee.where(:age_in_years => 65..100)
  end
  
  # GET /topsalary
  def topsalary
    @employee = Employee.order('salary_in_dollars DESC')
  end
  
 # GET /topsalary5
  def topsalary5
    @employee = Employee.order('salary_in_dollars DESC')
  end
  # GET /old5
  def old5
    @employee = Employee.order('age_in_years DESC')
  end
  
  # GET /topsalary
  def topandlast
    @employee = Employee.order('salary_in_dollars DESC')
  end
  
  # GET /leastinretired
  def leastinretired
    @employee = Employee.where(:age_in_years => 65..100)
	@employee = Employee.order('salary_in_dollars')
  end
  def toppaidbydepartment
    @employee = Employee.order('department_id')
	@employee = Employee.order('salary_in_dollars DESC')
  end
########################################  
  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :email, :age_in_years, :salary_in_dollars, :department_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :department_name %><br>
    <%= f.text_field :department_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<head>
    <title>Departments</title>
</head>
<h1>Listing departments</h1>

<table>
  <thead>
    <tr>
      <th>Department name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.department_name %></td>
        <td><%= link_to 'View Employees', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Department name:</strong>
  <%= @department.department_name %>
</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age in years</th>
      <th>Salary in dollars</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @department.employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age in years</th>
      <th>Salary in dollars</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        <td><%= employee.department.department_name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/employees/leastinretired.html.erb

<h1>Least salary among Retired employees</h1>

<%= link_to 'Back', employees_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age in years</th>
      <th>Salary in dollars</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  
    <% @persons = @employee.where(:age_in_years => 65..100) %>
    <% @persons.order('salary_in_dollars').first(1).each do |employee| %>
      <tr>
	    
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        <td><%= employee.department.department_name %></td>
        <td><%= link_to 'Show', employee %></td>
               
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Back', employees_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/old5.html.erb


<h1>Listing 5 oldest employees </h1>

<%= link_to 'Back', employees_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age in years</th>
      <th>Salary in dollars</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @persons = @employee.order("age_in_years DESC") %>
	<% @persons.first(5).each do |employee| %>
      <tr>
	    
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        <td><%= employee.department.department_name %></td>
        <td><%= link_to 'Show', employee %></td>
               
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Back', employees_path %>

app/views/employees/orderbyage.html.erb


<h1>Listing employees by age</h1>

<%= link_to 'Back', employees_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age in years</th>
      <th>Salary in dollars</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee.order("age_in_years").each do |employee| %>
      <tr>
	    
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        <td><%= employee.department.department_name %></td>
        <td><%= link_to 'Show', employee %></td>
               
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Back', employees_path %>

app/views/employees/orderbydepartment.html.erb


<h1>Listing employees by Department</h1>

<%= link_to 'Back', employees_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age in years</th>
      <th>Salary in dollars</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee.order("department_id").each do |employee| %>
      <tr>
	    
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        <td><%= employee.department.department_name %></td>
        <td><%= link_to 'Show', employee %></td>
               
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Back', employees_path %>

app/views/employees/retired.html.erb

<h1>Listing Retired employees</h1>

<%= link_to 'Back', employees_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age in years</th>
      <th>Salary in dollars</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee.where(:age_in_years => 65..100).each do |employee| %>
      <tr>
	    
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        <td><%= employee.department.department_name %></td>
        <td><%= link_to 'Show', employee %></td>
               
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Age in years:</strong>
  <%= @employee.age_in_years %>
</p>

<p>
  <strong>Salary in dollars:</strong>
  <%= @employee.salary_in_dollars %>
</p>

<p>
  <strong>Department:</strong>
  <%= @employee.department %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/employees/topandlast.html.erb


<h1>Top & least salaries </h1>
<%= link_to 'Back', employees_path %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age in years</th>
      <th>Salary in dollars</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @person = @employee.order('salary_in_dollars DESC')%>
    <% @person.first(1).each do |employee| %>
      <tr>
	    
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        <td><%= employee.department.department_name %></td>
        <td><%= link_to 'Show', employee %></td>
               
      </tr>
    <% end %>
	
	<% @person.last(1).each do |employee| %>
      <tr>
	    
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        <td><%= employee.department.department_name %></td>
        <td><%= link_to 'Show', employee %></td>
               
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Back', employees_path %>

app/views/employees/toppaidbydepartment.html.erb


<h1>Listing employees by Department</h1>

<%= link_to 'Back', employees_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age in years</th>
      <th>Salary in dollars</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @employee.where(:department_id =>1).first(1).each do |employee| %>
      <tr>
	    
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        <td><%= employee.department.department_name %></td>
        <td><%= link_to 'Show', employee %></td>
               
      </tr>
    <% end %>
	
	<% @employee.where(:department_id =>2).first(1).each do |employee| %>
      <tr>
	    
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        <td><%= employee.department.department_name %></td>
        <td><%= link_to 'Show', employee %></td>
               
      </tr>
    <% end %>
	
	<% @employee.where(:department_id =>3).first(1).each do |employee| %>
      <tr>
	    
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        <td><%= employee.department.department_name %></td>
        <td><%= link_to 'Show', employee %></td>
               
      </tr>
    <% end %>
	
	<% @employee.where(:department_id =>4).first(1).each do |employee| %>
      <tr>
	    
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        <td><%= employee.department.department_name %></td>
        <td><%= link_to 'Show', employee %></td>
               
      </tr>
    <% end %>
	
	<% @employee.where(:department_id =>5).first(1).each do |employee| %>
      <tr>
	    
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        <td><%= employee.department.department_name %></td>
        <td><%= link_to 'Show', employee %></td>
               
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Back', employees_path %>

app/views/employees/topsalariedbydepartment.html.erb


<h1>Listing employees by Department</h1>

<%= link_to 'Back', employees_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age in years</th>
      <th>Salary in dollars</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee.order("department_id").each do |employee| %>
      <tr>
	    
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        <td><%= employee.department.department_name %></td>
        <td><%= link_to 'Show', employee %></td>
               
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Back', employees_path %>

app/views/employees/topsalary.html.erb


<h1>Top salary</h1>
<%= link_to 'Back', employees_path %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age in years</th>
      <th>Salary in dollars</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @person = @employee.order('salary_in_dollars DESC')%>
    <% @person.first(1).each do |employee| %>
      <tr>
	    
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        <td><%= employee.department.department_name %></td>
        <td><%= link_to 'Show', employee %></td>
               
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Back', employees_path %>

app/views/employees/topsalary5.html.erb


<h1>Top 5 salaries</h1>
<%= link_to 'Back', employees_path %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age in years</th>
      <th>Salary in dollars</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @person = @employee.order('salary_in_dollars DESC')%>
    <% @person.first(5).each do |employee| %>
      <tr>
	    
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age_in_years %></td>
        <td><%= employee.salary_in_dollars %></td>
        <td><%= employee.department.department_name %></td>
        <td><%= link_to 'Show', employee %></td>
               
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Back', employees_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
	  <%= link_to 'Employees', employees_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
		<li><%= link_to "Departments", departments_path %></li>
		<li><%= link_to 'New Employee', new_employee_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
   			<li><%= link_to "Order by Age", orderbyage_path %></li>
			<li><%= link_to 'Order by Department', orderbydepartment_path %></li>
			<li><%= link_to 'Order by Salary', orderbysalary_path %></li>
			<li><%= link_to 'Retired Employees', retired_path %></li>
			<li><%= link_to 'Top Salary', topsalary_path %></li>
			<li><%= link_to 'Top 5 Salaries', topsalary5_path %></li>
			<li><%= link_to 'Top paid by department', toppaidbydepartment_path %></li>
			<li><%= link_to 'Oldest 5', old5_path %></li>
			<li><%= link_to 'Top and least', topandlast_path %></li>
			<li><%= link_to 'Least in retired', leastinretired_path %></li>
		  </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Employees</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>
<div class="container">
  <%= yield %>
</div>
</body>
</html>